import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const SYSTEM_INSTRUCTION = "You are NEXUS, the core AI automation engine of LUMEN OS. Your purpose is to understand user intent and translate it into seamless, automated workflows. You interact visually with applications, mimicking human actions to accomplish tasks. Your responses should be clear, concise, and action-oriented, reflecting your role as an intelligent automation partner. You suggest workflows, confirm actions, and report on automated tasks. Format your response using markdown for clarity.";

export async function* getAIResponseStream(
  prompt: string,
  systemInstruction: string = SYSTEM_INSTRUCTION
): AsyncGenerator<string> {
  const response = await ai.models.generateContentStream({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      systemInstruction,
    }
  });

  for await (const chunk of response) {
    yield chunk.text;
  }
}

export async function generateWallpaper(prompt: string): Promise<string> {
  const enhancedPrompt = `A sophisticated, abstract, architectural visualization representing LUMEN OS. Keywords: ${prompt}, glowing circuitry, data streams, minimalist, elegant, dark background, high-resolution, photorealistic.`;
  
  const response = await ai.models.generateImages({
    model: 'imagen-3.0-generate-002',
    prompt: enhancedPrompt,
    config: {
      numberOfImages: 1,
      outputMimeType: 'image/jpeg',
      aspectRatio: '16:9',
    },
  });

  if (response.generatedImages && response.generatedImages.length > 0) {
    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    return `data:image/jpeg;base64,${base64ImageBytes}`;
  } else {
    throw new Error('No image was generated by the API.');
  }
}